=== danja/2001/citnames/backup/iou/build/jproperties.dtd
<?xml version='1.0' encoding='UTF-8'?>

<!--
    DTD of XML wrapper for Properties
    Typical usage:

    <?xml version="1.0"?>

    <!DOCTYPE properties SYSTEM "properties.dtd">

    <properties>
        <propertylist name="wrox">
            <property name="website">www.wrox.com</property>
            <property name="email">someone@wrox.com</property>      
        </propertylist>
            ...
    </properties>
-->

  <!ELEMENT properties (#PCDATA|propertylist)*>

  <!ELEMENT property (#PCDATA)>
  <!ATTLIST property name CDATA #IMPLIED>

  <!ELEMENT propertylist (#PCDATA|property)*>
  <!ATTLIST propertylist name CDATA #IMPLIED>

=== danja/2001/citnames/backup/iou/dist/iouproperties.xml
<?xml version="1.0" encoding="UTF-8"?>
<!DOCTYPE properties SYSTEM "jproperties.dtd">
<!-- XML Wrapper for Properties -->
<properties>
	<propertylist name="pool">
		<property name="database">jdbc:mysql://localhost:3306/iou</property>
		<property name="driver">org.gjt.mm.mysql.Driver</property>
		<property name="catalog"></property>
		<property name="user">wrox</property>
		<property name="password">xorw</property>
		<property name="size">5</property>
		<property name="timeout">30</property>
		<property name="delay">10000</property>
		<property name="period">10000</property>
		<property name="lifespan">10000</property>
</propertylist>
 
</properties>

<!--   A few alternate drivers databases for non-DataSource pool  
jdbc:inetdae:localHost:1433
com.inet.tds.TdsDriver
			postgresql.Driver                       
			jdbc:postgresql://localhost:5432/wroxcon 
			sun.jdbc.odbc.JdbcOdbcDriver            
			jdbc:odbc:wroxcon                     
			org.gjt.mm.mysql.Driver                 
            	jdbc:mysql://localhost:3306/wroxcon     -->

=== danja/2001/citnames/backup/iou/src/semcat/semcatproperties.xml
<?xml version="1.0" encoding="UTF-8"?>
<!DOCTYPE properties SYSTEM "jproperties.dtd">
<!-- XML Wrapper for Properties -->
<properties>
	<propertylist name="pool">
		<property name="database">jdbc:odbc:Driver do MS Access (*.mdb);DBQ="D:/semcat.mdb"</property>
		<property name="driver">sun.jdbc.odbc.JdbcOdbcDriver</property>
		<property name="catalog"></property>
		<property name="user">admin</property>
		<property name="password">isacat</property>
		<property name="size">5</property>
		<property name="timeout">30</property>
		<property name="delay">10000</property>
		<property name="period">10000</property>
		<property name="lifespan">10000</property>
</propertylist>
 
</properties>

<!--   A few alternate drivers databases for non-DataSource pool 
 
  // jdbc:odbc:" + ODBCSource + ";DBQ=" + dbq + ";DefaultDir=" + defdir + "UID=Admin"
Driver={Microsoft Access Driver(*.mdb)};
jdbc:inetdae:localHost:1433
com.inet.tds.TdsDriver
			postgresql.Driver                       
			jdbc:postgresql://localhost:5432/wroxcon 
			sun.jdbc.odbc.JdbcOdbcDriver            
			jdbc:odbc:wroxcon                     
			org.gjt.mm.mysql.Driver                 
            	jdbc:mysql://localhost:3306/wroxcon     -->

=== danja/2001/citnames/backup/iou/build/iouproperties.xml
<?xml version="1.0" encoding="UTF-8"?>
<!DOCTYPE properties SYSTEM "jproperties.dtd">
<!-- XML Wrapper for Properties -->
<properties>
	<propertylist name="pool">
		<property name="database">jdbc:odbc:iou</property>
		<property name="driver">sun.jdbc.odbc.JdbcOdbcDriver</property>
		<property name="catalog"></property>
		<property name="user">wrox</property>
		<property name="password">xorw</property>
		<property name="size">5</property>
		<property name="timeout">30</property>
		<property name="delay">10000</property>
		<property name="period">10000</property>
		<property name="lifespan">10000</property>
</propertylist>
 
</properties>

<!--   A few alternate drivers databases for non-DataSource pool  
jdbc:inetdae:localHost:1433
com.inet.tds.TdsDriver
			postgresql.Driver                       
			jdbc:postgresql://localhost:5432/wroxcon 
			sun.jdbc.odbc.JdbcOdbcDriver            
			jdbc:odbc:wroxcon                     
			org.gjt.mm.mysql.Driver                 
            	jdbc:mysql://localhost:3306/wroxcon     -->
